---
title: "hcpd_analysia"
output: html_document
date: "2024-09-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(broom)
library(tidyr)
library(purrr)
library(broom)
```

```{r}
metrics = read.csv("~/Desktop/macedo_tract/outputs/metrics_df.csv")

# Clean the data, remove NANs and scale regression variables
cleaned_metrics <- metrics %>%
  drop_na(score, sex, interview_age, t1_neighbor_corr, brain_size)

cleaned_metrics$t1_neighbor_corr <- scale(cleaned_metrics$t1_neighbor_corr)
cleaned_metrics$brain_size <- scale(cleaned_metrics$brain_size)
cleaned_metrics$interview_age <- scale(cleaned_metrics$interview_age)
cleaned_metrics$sex <- scale(cleaned_metrics$sex)
```

```{r}
# Create linear regression model function, with a toggle variable "brain_size" which determines whether or not to include brain size in the model.
linear_model <- function(df, brain_size=TRUE) {
  if (brain_size) {lm(score ~ sex + interview_age + t1_neighbor_corr + brain_size, data = df)} 
  else {lm(score ~ sex + interview_age + t1_neighbor_corr, data = df)}}

linear_reduced <- function(df, brain_size=TRUE) {
  if (brain_size) {lm(score ~ sex + t1_neighbor_corr + brain_size, data = df)} 
  else {lm(score ~ sex + t1_neighbor_corr, data = df)}}
```

```{r}
# Group the dataframe by the bundle and metric column and apply the fit_model function
results <- cleaned_metrics %>%
  group_by(metric, bundle) %>%
  do(model = linear_model(.))

# Reduced results (for r^2 analysis, excludes age term)
reduced_results <- cleaned_metrics %>%
  group_by(metric, bundle) %>%
  do(model = linear_reduced(.))
```

** Run either this chunk or the "linear_model" chunk, depending on if you'd like to have a GAM or linear model. ** 
```{r}
# GAM with smooth term for age.
gam_age <- function(df) {
  gam(score ~ sex + s(interview_age) + t1_neighbor_corr + brain_size, data = df)}

results <- cleaned_metrics %>%
  group_by(metric, bundle) %>%
  do(model = gam_age(.))

summary(results$model[[1]])
plot(results$model[[1]])
```

```{r}
# FDR correct "age" p-values per group of metrics, and then check how many p-values survive per metric.
results$tstat <- 0 
results$pval <-0 
for(i in 1:nrow(results)) {
    results$tstat[i] = broom::tidy(results$model[[i]])  %>%
          filter(term == "s(interview_age)") %>%
          pull(statistic)
    
    results$pval[i] = broom::tidy(results$model[[i]])  %>%
      filter(term == "s(interview_age)") %>%
      pull(p.value)}

results <- results %>%
  group_by(metric) %>%
  mutate(fdr_pvals = p.adjust(pval, method = "fdr")) %>%
  ungroup()

results <- results %>%
  group_by(metric) %>%
  mutate(surviving_ps = fdr_pvals < 0.05)
```

```{r}
metric_dict <- results %>%
  group_by(metric) %>%
  summarize(sum_surviving_ps = sum(surviving_ps)) %>%
  ungroup()

metric_dict <- metric_dict %>%
  arrange(desc(sum_surviving_ps)) # order

metric_dict$metric <- factor(metric_dict$metric, levels = metric_dict$metric) # maintain order for graph
```

```{r}
ggplot(metric_dict, aes(x = metric, y = sum_surviving_ps)) +
  geom_col(fill = "#1f77b4") +
  geom_hline(yintercept = 56, color = "red", linewidth = 0.5) +
  labs(title = "FDR-corrected p-values for the age term in the linear regression with brain size",
       x = "Metric",
       y = "Sum of Surviving PS") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
main_metrics <- c('area_of_end_region_1_mm2', 'area_of_end_region_2_mm2',
       'diameter_mm', 'dti_fa', 'md', 'mean_length_mm',
       'radius_of_end_region_1_mm', 'radius_of_end_region_2_mm', 
       'total_radius_of_end_regions_mm', 'total_surface_area_mm2',
       'trunk_volume_mm3',
       'volume_mm3')
results_main <- results %>%
  filter(metric %in% main_metrics)
```


```{r, fig.width=16, fig.height=8}
ggplot(results, aes(x = tstat, fill = metric)) +
    geom_density(alpha = 0.5) +  # Density plot with transparency
    geom_vline(xintercept = 0, color = "red") +
    facet_wrap(~ metric) +  # Create a separate plot for each unique value in bundle
    labs(title = "Distribution of t statistic for age in linear regression by metric",
         x = "t_stat",
         y = "Density") +
    theme_minimal() +
    theme(legend.position = "none")  # Remove legend for clarity if needed
```

Take the partial Rs

```{r}
# Calculate the partial R^2 for 'age'
results$partial_r2 <- 0
for(i in 1:nrow(results)) {
  full_r2 <- summary(results$model[[i]])$r.squared
  reduced_r2 <- summary(reduced_results$model[[i]])$r.squared
  results$partial_r2[[i]] <- (full_r2 - reduced_r2)/reduced_r2
}
```

```{r, fig.width=16, fig.height=8}
ggplot(results, aes(x = partial_r2, fill = metric)) +
    geom_density(alpha = 0.5) +  # Density plot with transparency
    geom_vline(xintercept = 0, color = "red") +  # Add vertical line at x = 0
    facet_wrap(~ metric) +  # Create a separate plot for each unique value in metric
    xlim(c(-1, 2)) +
    ylim(c(0, 5)) +
    labs(title = "Distribution of Partial R^2 for Age in Linear Regression by Metric",
         x = "Partial R^2",
         y = "Density") +
    theme_minimal() +
    theme(legend.position = "none")  # Remove legend for clarity if needed
```


